version: '3.0'

services:
  mock_balancer:
    container_name: mock_balancer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - network
    depends_on:
      - mock_server1
      - mock_server2
      - mock_server3
      - mock_server4
      - mock_server5
    restart: on-failure

  mock_server1:
    build:
      context: .
      dockerfile: ./mock.dockerfile
    ports:
      - "8001:8001"
    environment:
      - MOCK_API_HOST=${MOCK_API_HOST:-0.0.0.0}
      - MOCK_API_PORT=8001
      - MOCK_SERVER_NUMBER=1
    networks:
      - network

  mock_server2:
    build:
      context: .
      dockerfile: ./mock.dockerfile
    ports:
      - "8002:8002"
    environment:
      - MOCK_API_HOST=${MOCK_API_HOST:-0.0.0.0}
      - MOCK_API_PORT=8002
      - MOCK_SERVER_NUMBER=2
    networks:
      - network

  mock_server3:
    build:
      context: .
      dockerfile: ./mock.dockerfile
    ports:
      - "8003:8003"
    environment:
      - MOCK_API_HOST=${MOCK_API_HOST:-0.0.0.0}
      - MOCK_API_PORT=8003
      - MOCK_SERVER_NUMBER=3
    networks:
      - network

  mock_server4:
    build:
      context: .
      dockerfile: ./mock.dockerfile
    ports:
      - "8004:8004"
    environment:
      - MOCK_API_HOST=${MOCK_API_HOST:-0.0.0.0}
      - MOCK_API_PORT=8004
      - MOCK_SERVER_NUMBER=4
    networks:
      - network

  mock_server5:
    build:
      context: .
      dockerfile: ./mock.dockerfile
    ports:
      - "8005:8005"
    environment:
      - MOCK_API_HOST=${MOCK_API_HOST:-0.0.0.0}
      - MOCK_API_PORT=8005
      - MOCK_SERVER_NUMBER=5
    networks:
      - network

networks:
  network:
    driver: bridge